name: pnpm my-website
on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Debug - List files before build
      run: |
        echo "=== Files before build ==="
        ls -la
        echo "=========================="
    - name: Build app
      run: pnpm run build
    - name: Debug - List files after build
      run: |
        echo "=== Files after build ==="
        ls -la
        echo "=========================="
    - name: Debug - Check for out folder
      run: |
        if [ -d "out" ]; then
          echo "✅ out folder exists"
          echo "Contents of out:"
          ls -la out/
        else
          echo "❌ out folder does not exist"
        fi
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4